version: '3'
services:
    web:
        build: .
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ~/Downloads:/usr/share/nginx/html
        ports:
            - 8080:80
